# .github/workflows/python-tests.yml

name: Python Tests

on:
  push:
    branches:
      - main  # Change this to match your main branch
  pull_request:
    branches:
      - main  # Add other branches if needed

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    strategy:
      matrix:
        python-version: [3.9.7]  # Test on multiple Python versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository code

    - name: Set up Python 3.9.7
        uses: actions/setup-python@v4  # Set up Python environment
        with:
          python-version: '3.9.7'  # Use Python version 3.9.7

    - name: Upgrade pip
      run: python -m pip install --upgrade pip  # Upgrade pip to the latest version

    - name: Run tests
      run: python -m unittest discover -s test -p "*.py"  # Discover and run tests